# Generated by Django 6.0.5 on 2026-05-26 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('gentilico', models.CharField(blank=True, max_length=255, null=True)),
                ('apelido', models.CharField(blank=True, max_length=255, null=True)),
                ('governante', models.CharField(blank=True, max_length=255, null=True)),
                ('tamanho', models.CharField(max_length=255)),
                ('descrição', models.TextField(blank=True, default=0, null=True)),
                ('historia', models.TextField(blank=True, default=0, null=True)),
                ('geografia', models.TextField(blank=True, default=0, null=True)),
                ('defesas', models.TextField(blank=True, default=0, null=True)),
                ('lei_e_ordem', models.TextField(blank=True, default=0, null=True)),
                ('exportacoes', models.TextField(blank=True, default=0, null=True)),
                ('importacoes', models.TextField(blank=True, default=0, null=True)),
                ('cultura_e_Sociedade', models.TextField(blank=True, default=0, null=True)),
                ('notas', models.TextField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especie', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=255)),
                ('antecedente', models.CharField(max_length=255)),
                ('talentos', models.CharField(max_length=255)),
                ('altura', models.CharField(max_length=255)),
                ('peso', models.CharField(max_length=255)),
                ('divindade', models.CharField(max_length=255)),
                ('cidade_natal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npcs_nascidos_aqui', to='gerenciador.lugar')),
                ('local_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npcs_presentes_aqui', to='gerenciador.lugar')),
            ],
        ),
    ]
